version: "3.8"

services:
    flask_api_gpt:
        networks:
            - ai_net
        build: .
        restart: on-failure
        command: python3 app.py
        volumes:
            - .:/app
        ports:
            - "5001:5000"

networks:
    ai_net:
        driver: bridge
